#!/bin/sh
# 鸿蒙容器中 JS 三方库编译前的环境检测与安装。
# 检测 busybox、make、cmake、vim、git、python；缺失时优先用 brew 安装；
# 若无 brew，则从仓库批量下载至 /opt 后解压，并写入环境变量配置。

# --- 与预编译包一致的版本（无 brew 分支使用）---
OHOS_BUSYBOX_VER=1.37.0
OHOS_MAKE_VER=4.4.1
OHOS_CMAKE_VER=4.1.2
OHOS_VIM_VER=9.2.0150
OHOS_GIT_VER=2.45.2
OHOS_PYTHON_VER=3.14.3

OHOS_ARCH_TAG=ohos-arm64
DOWNLOAD_BASE=https://github.com/Harmonybrew
PKG_CACHE=/opt/.ohos-build-env-pkg
ENV_SNIPPET=/opt/ohos-build-env.sh
VIM_SHIM_DIR=/opt/ohos-build-env-bin

log() {
    printf '%s\n' "[build-env] $*"
}

err() {
    printf '%s\n' "[build-env] ERROR: $*" >&2
}

command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# 若仅有 nvim 而无 vim，则通过 shim 满足「vim」检测
ensure_vim_shim() {
    command_exists vim && return 0
    if command_exists nvim; then
        mkdir -p "$VIM_SHIM_DIR"
        ln -sfn "$(command -v nvim)" "$VIM_SHIM_DIR/vim"
        log "已创建 vim -> nvim 包装: $VIM_SHIM_DIR/vim"
    fi
}

check_busybox() {
    command_exists busybox
}

check_make() {
    command_exists make
}

check_cmake() {
    command_exists cmake
}

check_vim() {
    command_exists vim || command_exists nvim
}

check_git() {
    command_exists git
}

check_python() {
    command_exists python3 || command_exists python
}

need_busybox=
need_make=
need_cmake=
need_vim=
need_git=
need_python=

check_busybox || need_busybox=1
check_make || need_make=1
check_cmake || need_cmake=1
check_vim || need_vim=1
check_git || need_git=1
check_python || need_python=1

if [ -z "$need_busybox$need_make$need_cmake$need_vim$need_git$need_python" ]; then
    log "所需工具均已存在，无需安装。"
    ensure_vim_shim
    exit 0
fi

log "缺失项检测: busybox=${need_busybox:-ok} make=${need_make:-ok} cmake=${need_cmake:-ok} vim=${need_vim:-ok} git=${need_git:-ok} python=${need_python:-ok}"

install_with_brew() {
    pkgs=
    [ -n "$need_busybox" ] && pkgs="$pkgs busybox"
    [ -n "$need_make" ] && pkgs="$pkgs make"
    [ -n "$need_cmake" ] && pkgs="$pkgs cmake"
    [ -n "$need_vim" ] && pkgs="$pkgs vim"
    [ -n "$need_git" ] && pkgs="$pkgs git"
    [ -n "$need_python" ] && pkgs="$pkgs python"
    # shellcheck disable=SC2086
    log "使用 brew 安装:$pkgs"
    brew install $pkgs
}

# 下载单个 Harmonybrew 包到 PKG_CACHE，若 /opt 下已解压则跳过
download_ohos_pkg() {
    name=$1
    ver=$2
    file=$name-$ver-$OHOS_ARCH_TAG.tar.gz
    url=$DOWNLOAD_BASE/ohos-$name/releases/download/$ver/$file
    inst_dir="/opt/$name-$ver-$OHOS_ARCH_TAG"

    if [ -d "$inst_dir" ]; then
        log "已存在安装目录，跳过: $inst_dir"
        return 0
    fi

    mkdir -p "$PKG_CACHE"
    archive="$PKG_CACHE/$file"
    if [ -f "$archive" ]; then
        log "本地已有压缩包，跳过下载: $archive"
    else
        log "下载: $name $ver -> $archive"
        if ! curl -fSLo "$archive" --connect-timeout 60 --retry 3 --retry-delay 2 "$url"; then
            err "下载失败: $url"
            return 1
        fi
    fi

    log "解压到 /opt: $file"
    if ! tar -zxf "$archive" -C /opt; then
        err "解压失败: $archive"
        return 1
    fi
    return 0
}

install_from_repo_bulk() {
    log "未检测到 brew，从仓库批量下载并解压到 /opt …"
    mkdir -p /opt

    failed=0
    if [ -n "$need_busybox" ]; then
        download_ohos_pkg busybox "$OHOS_BUSYBOX_VER" || failed=1
    fi
    if [ -n "$need_make" ]; then
        download_ohos_pkg make "$OHOS_MAKE_VER" || failed=1
    fi
    if [ -n "$need_cmake" ]; then
        download_ohos_pkg cmake "$OHOS_CMAKE_VER" || failed=1
    fi
    if [ -n "$need_vim" ]; then
        download_ohos_pkg vim "$OHOS_VIM_VER" || failed=1
    fi
    if [ -n "$need_git" ]; then
        download_ohos_pkg git "$OHOS_GIT_VER" || failed=1
    fi
    if [ -n "$need_python" ]; then
        download_ohos_pkg python "$OHOS_PYTHON_VER" || failed=1
    fi

    if [ "$failed" -ne 0 ]; then
        err "批量安装过程中有步骤失败。"
        exit 1
    fi

    ensure_vim_shim
}

write_env_snippet() {
    # 仅在无 brew 批量安装后需要把 /opt 下工具链拼进 PATH；brew 路径通常已在登录环境中
    if command_exists brew; then
        return 0
    fi

    roots=
    roots="$roots /opt/busybox-$OHOS_BUSYBOX_VER-$OHOS_ARCH_TAG/bin"
    roots="$roots /opt/make-$OHOS_MAKE_VER-$OHOS_ARCH_TAG/bin"
    roots="$roots /opt/cmake-$OHOS_CMAKE_VER-$OHOS_ARCH_TAG/bin"
    roots="$roots /opt/vim-$OHOS_VIM_VER-$OHOS_ARCH_TAG/bin"
    roots="$roots /opt/git-$OHOS_GIT_VER-$OHOS_ARCH_TAG/bin"
    roots="$roots /opt/python-$OHOS_PYTHON_VER-$OHOS_ARCH_TAG/bin"
    roots="$roots $VIM_SHIM_DIR"

    new_path=
    for d in $roots; do
        if [ -d "$d" ]; then
            if [ -z "$new_path" ]; then
                new_path=$d
            else
                new_path="$d:$new_path"
            fi
        fi
    done

    if [ -z "$new_path" ]; then
        log "未找到可加入 PATH 的目录，跳过写入 $ENV_SNIPPET"
        return 0
    fi

    log "写入环境变量: $ENV_SNIPPET"
    umask 022
    {
        printf '%s\n' '# Generated by build-env.sh — source this file before building JS ports.'
        printf '%s\n' "export PATH=\"$new_path:\$PATH\""
    } >"$ENV_SNIPPET.tmp" && mv -f "$ENV_SNIPPET.tmp" "$ENV_SNIPPET"

    log "请在当前 shell 执行: . $ENV_SNIPPET"
    log "或将其加入 ~/.profile / CI 镜像入口脚本。"
}

if command_exists brew; then
    install_with_brew
else
    install_from_repo_bulk
fi

write_env_snippet

log "环境准备完成。"
